### ISSUE TITLE
how its work?

### ISSUE THREAD

**Issue by h9nt** [evikza/tiktok-user-stats#1]

**Comment by evikza** [comment]
@o7dn 

Hi. 👋 I fixed the problem. It's been a long time since I've updated the repository. 
TikTok developers often change the page structure.

**Comment by h9nt** [comment]
ah okay thanks

**Comment by evikza** [comment]
⚠️ Important:

Now you also need an `msToken` cookie for the request. You can take it from your browser, use Selenium WebDriver or generate it yourself.

**Comment by o7dn** [comment]
How do I get the token and how can I make it so that other users can also search for your username?
